#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  9 16:59:46 2017

@author: estelleaflalo
"""

def loss(y_true,y_pred):
    c=0
    temp=np.zeros(y_pred.shape[0])
    for i in range(y_pred.shape[0]):
        if y_pred[i] in y_true.tolist():
            c+=1
            temp[i]=float(c)/(i+1)
        else :
            temp[i]=0
    return sum(temp)/min(y_true.shape[0],10)
     